### ISSUE TITLE
Uncaught TypeError: undefined is not a function:274

### ISSUE THREAD

**Issue by puch** [miroshko/Synzer#1]
Скрипту неизвестен метод createStereoPanner, из-за этого приложение не работает.

**Comment by miroshko** [comment]
возможно браузер не поддерживает. добавлю проверку
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createStereoPanner
Browser compatibility
Сhrome 42.0
Firefox (Gecko) 37.0
Internet Explorer Not supported
Opera Not supported
Safari (WebKit) Not supported

**Comment by puch** [comment]
Да, точно. Смотрел в Яндекс.Браузере (WebKit). В Хроме работает. Получилось круто, восхищаюсь!
